### PR TITLE
Add instructions for using [Nextclade](https://clades.nextstrain.org/)

### PR DESCRIPTION
**Pull request by WillHannon-MCB**
@jbloom, here's my proposed solution for integrating our data with Nextclade.

Louise and Jordan updated the `H5Nx clade 2.3.4.4` reference dataset so that it's possible to call mutations relative to `A/American_wigeon/North_Carolina/AH0182517/2022`, which has the same amino acid sequence as `A/American Wigeon/South Carolina/USDA-000345-001`. The HA numbering of `H5Nx clade 2.3.4.4` is the same as `sequential_sites` in our DMS data.

I added instructions for identifying mutations with Nextclade to the [summary page](https://dms-vep.org/Flu_H5_American-Wigeon_South-Carolina_2021-H5N1_DMS/summary.html) of the H5 website.

This may be an imperfect solution because `A/American_wigeon/North_Carolina/AH0182517/2022` has at least one nucleotide substitution relative to `A/American Wigeon/South Carolina/USDA-000345-001` (G270T). It might not matter for calling amino acid mutations, but I'm sure Louise and Jordann would add `A/American Wigeon/South Carolina/USDA-000345-001` to  `H5Nx clade 2.3.4.4` if this solution seems reasonable.

### CODE REVIEW

**Review by jbloom — COMMENTED** [review]
@WillHannon-MCB, nice start on this. A few suggestions:

- This should really have a title more like "Identifying HA mutations in a new sequence" as that is what it is instructions on how to do.
- Probably make it a new subpage, not just tack it onto the *Summary*. 
- I don't think we should try to point people to the CSV of all the DMS values in `phenotypes.csv`. That is not a useful way to look at the data. I think we should just say "This gives you the mutations in sequential numbering, you can convert them to H3 numbering using the [page with site numbering explanation, which is a subpage of this page already], and then look them up in the interactive plots".

Does this make sense? All we are really doing here is  providing instructions on how to convert an arbitrary sequence into a list of mutations relative to our DMS strain, so I think we should make that clear.

**Comment by WillHannon-MCB** [comment]
All of this makes sense!

**Review by jbloom — CHANGES_REQUESTED** [review]
@WillHannon-MCB, looks good for the most part. I do think you should add instructions to specify that the HA amino-acid mutations relative to the DMS strain are in the column named `relativeMutations['A/American_wigeon/North_Carolina/AH0182517/2022'].aaSubstitutions`, and the column named `aaSubstitutions` still only has the mutations relative to the default Nextclade reference strain.

**Comment by WillHannon-MCB** [comment]
@jbloom, I added a note to my instructions about `aaSubstitutions`.

**Review by jbloom — APPROVED** [review]
Approved.

**Pull request merged**
