### PR TITLE
Remove pull request hook

### PR DESCRIPTION
**Pull request by WillHannon-MCB**
I'm not sure what's causing the `deploy` action to fail, but it's related to the `git` history of the `ghpages` branch. The problem might occur because the `deploy` action runs on `pull requests` when they're *opened*, *updated*, etc... not when they're approved and merged. Therefore, the `deploy` action is run from `main` *and* any branch with an open `pull request`. This could lead to strange issues with the history of the `ghpages` branch.

I removed the `pull requests` hook. The `push` hook should be sufficient.

### CODE REVIEW

**Comment by jbloom** [comment]
Are you sure this will not eliminate checks for whether the VitePress docs build correctly without error? It is good to have that checked on pull requests so that a branch is not merged that fails to build VitePress docs.

**Comment by WillHannon-MCB** [comment]
That's a fair point. I'll see if I can run everything up to the `build` stage unless it's a push to `main`.

**Comment by jbloom** [comment]
@WillHannon-MCB, I will merge this here. Do you want to make a similar pull request to `dms-vep-pipeline-3` since that is the template people are copying?

**Comment by WillHannon-MCB** [comment]
Yep, on it!

**Pull request merged**
